### On peut définir des variables de cette façon
@endpoint = http://localhost:3000

################################
###          evenements          ###
################################

### récupération d'un évenement
GET {{ endpoint }}/route404

### récupération des évenements

GET {{ endpoint }}/evenements

### récupération d'un évenements
GET {{ endpoint }}/evenenements/1

### ajouter un évenement
POST {{ endpoint }}/lists
content-type: application/x-www-form-urlencoded

title=evenement à ajouter

### modifier un évènement
PATCH {{ endpoint }}/evenements/1
content-type: application/x-www-form-urlencoded

title=nouveau titre pour l'évenement 1

### supprimer un évènements
DELETE {{ endpoint }}/evenements/7

