### On peut définir des variables de cette façon
@endpoint = http://localhost:3040

################################
###          evenements          ###
################################

### récupération d'un évenement
GET {{ endpoint }}/route404

### récupération des évenements
GET {{ endpoint }}/events

### récupération d'un évenement
GET {{ endpoint }}/events/3

### ajouter un évenement
POST {{ endpoint }}/events
content-type: application/x-www-form-urlencoded

title=jouer au foot&description=profiter des joies du foot&date_hour=2022-02-26 18:50:00&capacity=20&price=GRATUIT&adress=11 rue de la liberté 29400 pencran&image=http://&user_id=3

### modifier un évènement
PATCH {{ endpoint }}/events/1
content-type: application/x-www-form-urlencoded

title=nouveau titre pour l'évenement 1

### supprimer un évènement
DELETE {{ endpoint }}/events/1

################################
###          login        ###
################################

### se connecter
POST {{ endpoint }}/login
content-type: application/x-www-form-urlencoded

email=raf@raf.raf&password=rafifou

################################
###          Signin        ###
################################

### s'inscrire
POST {{ endpoint }}/signin
content-type: application/x-www-form-urlencoded

email=al@allo.allo&firstname=Jean&lastname=Bon&password=jambon&birthday=2000-01-01&image=www.image.fr&pseudo=lalala&passwordConfirm=jambon

################################
###          Profil     ###
################################

### supprimer un profil
DELETE {{ endpoint }}/profils/2

