### On peut définir des variables de cette façon

@endpoint = http://localhost:3001


################################
###          evenements          ###
################################

### récupération d'un évenement
GET {{ endpoint }}/route404

### récupération des évenements
GET {{ endpoint }}/events

### récupération d'un évenement
GET {{ endpoint }}/events/2

### ajouter un évenement
POST {{ endpoint }}/events
content-type: application/x-www-form-urlencoded

id=5&title=Match de foot à la télé&description=Soiree match Lille/PSG et apéro dans un bar à Paris XVII (lieu à définir ensemble)&date=2022-02-28T14:00:00.000Z&capacity=10&price=GRATUIT&adress=rue du parc&city=Paris&category=sport&counter=1&user_id=1
### modifier un évènement
PATCH {{ endpoint }}/events/1
content-type: application/x-www-form-urlencoded

id=10&title=Match de foot à la télé&description=Soiree match Lille/PSG et apéro dans un bar à Paris XVII (lieu à définir ensemble)&date=2022-02-28T14:00:00.000Z&capacity=10&price=GRATUIT&adress=rue du parc&city=Paris&category=sport&counter=1&user_id=1

### supprimer un évènement
DELETE {{ endpoint }}/events/2

################################
###          login        ###
################################

### se connecter
POST {{ endpoint }}/login
content-type: application/x-www-form-urlencoded

email=raf@raf.raf&password=rafifou

################################
###          Signin        ###
################################

### s'inscrire
POST {{ endpoint }}/signin
content-type: application/x-www-form-urlencoded

email=alo@alo.allo&firstname=Jean&lastname=Bon&password=jambon&birthday=2000-01-01&image=www.image.fr&pseudo=lalala&passwordConfirm=jambon

################################
###          Profil     ###
################################

### supprimer un profil
DELETE  {{ endpoint }}/profils/4


